[package]
name = "granne"
version = "0.1.0"
authors = ["Erik Larsson <erik.ie.larsson@gmail.com>"]
license = "MIT"
links = "blas"
build = "build.rs"
edition = "2018"

[dependencies]
blas = "0.20.0"
byteorder = "1.2.1"
bytes = "0.4"
clap = "2.28.0"
crossbeam = "0.3.2"
flate2 = "0.2.19"
hashbrown = "0.1"
madvise = "0.1.0"
memmap = "0.6.2"
ordered-float = "0.5.0"
parking_lot = "0.7"
pbr = "1.0.0"
rand = "0.3"
rayon = "1.0"
revord = "0.0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.2"
slice_vector = {path = "slice_vector/"}
time = "0.1"
toml = "0.4"
